language: php

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files
    - node_modules

addons:
  apt:
    packages:
      - nginx
  code_climate:
    repo_token:
      secure: "Q8UTbZeQUGcS9+UwZt1TwtAh7gAOygoGu7TT0d7Q8c9JRK4piRQLA8juFyFICI/V5GS9mO5u0dw00ZStZj2uWuzUKdFH+eewG4wRFPiBHcQy9uS7JM7UBT2EGdQ3kKKUvznZhjxlu3SV36Fq2IqKM/kbWRuPuAjyyoyLFDVz4yNirKmggOm50G5CaHYvj4N4tEW3NvcxBrFaAo+G1mz7l5M75Y6oQYcs547+EmNtZUq/FCqEOXcDZN8QOe+sQ9vQIHF0v7wSqGqIvcj+krQuOTn3+oFPj+6vc5FnaeB52XGWo4D/MN4WZggi2GZh8qSxGqAhbPh+1AW7XDxfvSZ7x91vpjGoVUW2J6vgM+GKlsU1QG7HNj5Cm7oYIdMu+mDB5MkU/Ywuhy4r9AJL5LqyKBsSZS/HKWKrxI6Xeu5MNuR3nBBRo+nwamB+u+IBd/ohmc/bdqdoLVqcvS4dnlc9EdYKS7tCJ8biB9QxdT54zwVa6iskdKAF898d+g5TD/WeWlhjlq+fSwUwAw4mRrHGL3XXtKH2Ob5FsDGMyahyg4oIPXmwOGGhQ10qfOQIVtqp4xmZ4SWItPI4kJoYGily4XVwbIOAGZ69T4MISJUMWFupu9RETWC0NSB5iCpHVHzg8fGVOi/L+GkLHSKXMojaOHH4cJ8o3b3yUCN9NQap4cs="
  sauce_connect: true

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - nightly

env:
  - WP_VERSION=nightly
  - WP_VERSION=latest
  - WP_VERSION=4.7.2
  - WP_VERSION=4.7.1
  - WP_VERSION=4.7

matrix:
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly
  fast_finish: true

before_install:
  # Set environment variables
  - if [[ $(phpenv version-name) == "7.0" && "$WP_VERSION" == "latest" ]]; then
      export WITH_PHPCS=true;
    fi

  - if [[ $(phpenv version-name) == "7.1" && "$WP_VERSION" == "latest" ]]; then
      export WITH_COVERAGE=true;
    fi

  # Disable xdebug to speed up the build unless test coverage is needed
  - if [[ "$WITH_COVERAGE" != "true" && $(phpenv version-name) != "nightly" ]]; then
      phpenv config-rm xdebug.ini;
    fi

  # Install TypistTech/travis-nginx-wordpress
  - git clone --depth=1 https://github.com/TypistTech/travis-nginx-wordpress $HOME/setup
  - source $HOME/setup/travis/setup.sh $HOME/setup
  - install-nginx
  - install-wordpress
  - prepare-codeception

  # WordPress coding standard
  - if [[ "$WITH_PHPCS" == "true" ]]; then
      install-phpcs;
    fi

  # Install npm packages
  - npm install
  # Build the production plugin
  - grunt build
  # Activate the plugin
  - wp plugin install ./release/wp-better-settings.zip --force --activate --path=/tmp/wordpress
  # Export a dump of plugin-activated database to the _data folder
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql --path=/tmp/wordpress

  # Get back to Travis build dir
  - cd $TRAVIS_BUILD_DIR

install:
  # Build tests
  - composer install --prefer-dist --no-interaction --no-suggest
  - vendor/bin/codecept build

script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then
      vendor/bin/codecept run --debug -vvv --coverage --coverage-xml;
    else
      vendor/bin/codecept run --debug -vvv;
    fi

  - if [[ "$WITH_PHPCS" == "true" ]]; then
      phpcs --standard=ruleset.xml;
    fi

after_success:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then
      composer require codeclimate/php-test-reporter --dev;
      vendor/bin/test-reporter --no-interaction --coverage-report=tests/_output/coverage.xml;
    fi

deploy:
  provider: releases
  api_key:
    secure: k7m0Dld63XcOzfcwZ9jL1Y5O9vEsKoxt9RPa49GSe6YzcLk5Utak8ImNA9x+JKGIEiO3npp3YJ/HB457Hxjjfwl3pqAod2CJR7nFpoPac3qsy13LJj8dGPH87+crfwnfBJ9S9w6+/dWVwYjk++NjPP2ZPOBCg5An2Mhm+V/TbkQZWCjerc8nEo6SIviJNi+TocV2vDuihF3mot8iJYUKcbBn902Wns8QpvtZXISxHD30p5ImgS08dYSal8x5uFw5l70uhAm9cxEqD/QQiPb8JLbugeWnZfQtFs0q/CYZyoN3KU5rlPt8R6rnUBkCJRUqqveMVnzjHOvMLf/a4AobM4XpJadwRS2pGwuXCeYHYe79l0ILvAIW6UWPiw0lFit/7+d0VWlz0hhysYbSM+npd6vXpgT0dzd4tGsxMGqKIgI68gdpelraUlAQrllhbC7Bydh6K4ZMlTmns5K6Ofs9f2esTUhTbXoaNOCXuQaJYAL8gzDwvbUNXNf5+pDEYEaqGPGDXQCMU8qrhja3xR2/N+ki6jpsfIOtr4mCcPJGiPZcWH1comLQpfRysb4RSwnkW7auZcqCTnPkpRcbhBFFrC6Zrw1uSHbv209A+88Tt6z25Jmay5TLsXR0JBc4HCWEdKWbLsnvVcj5G75Xxh6saDOkPY5zpQeIGblwdFvZGDw=
  file: release/wp-better-settings.zip
  skip_cleanup: true
  on:
    condition: "$WP_VERSION = latest"
    php: 7.0
    tags: true
    repo: TypistTech/wp-better-settings
