language: php

sudo: false

branches:
  only:
    - master
    - /^(?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+)$/

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files
    - node_modules

addons:
  apt:
    packages:
      - jq
      - nginx

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.0
  - 7.1
  - nightly

env:
  - WP_VERSION=nightly
  - WP_VERSION=latest WITH_COVERAGE=true WITH_PHPCS=true
  - WP_VERSION=4.7.2
  - WP_VERSION=4.7.1
  - WP_VERSION=4.7

matrix:
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly
  fast_finish: true

before_install:
  # Set environment variables
  - if [[ $(phpenv version-name) == "nightly" ]]; then
      export WITH_COVERAGE=false;
    fi

  # Disable xdebug to speed up the build unless test coverage is needed
  - if [[ "$WITH_COVERAGE" != "true" && $(phpenv version-name) != "nightly" ]]; then
      phpenv config-rm xdebug.ini;
    fi

  # Install helper scripts
  - composer global require -n --prefer-dist "typisttech/travis-nginx-wordpress:^1.1"
  - export PATH=$HOME/.composer/vendor/bin:$PATH
  - tnw-install-nginx
  - tnw-install-wordpress
  - tnw-prepare-codeception

  # WordPress coding standard
  - if [[ "$WITH_PHPCS" == "true" ]]; then
      tnw-install-wpcs;
    fi

  # Install npm packages
  - npm update
  # Build the production plugin
  - grunt build
  # Activate the plugin
  - wp plugin install ./release/wp-better-settings.zip --force --activate --path=/tmp/wordpress
  # Export a dump of plugin-activated database to the _data folder
  - wp db export $TRAVIS_BUILD_DIR/tests/_data/dump.sql --path=/tmp/wordpress

install:
  # Get back to Travis build dir
  - cd $TRAVIS_BUILD_DIR

  # Build tests
  - composer install --prefer-dist --no-interaction --no-suggest
  - vendor/bin/codecept build -n

script:
  # Get back to Travis build dir
  - cd $TRAVIS_BUILD_DIR

  - if [[ "$WITH_COVERAGE" == "true" ]]; then
      vendor/bin/codecept run -n -vvv --coverage --coverage-xml;
    else
      vendor/bin/codecept run -n -vvv;
    fi

  - if [[ "$WITH_PHPCS" == "true" ]]; then
      phpcs --standard=ruleset.xml;
    fi

after_script:
  - if [[ "$WITH_COVERAGE" == "true" ]]; then
      tnw-upload-coverage-to-scrutinizer;
    fi

deploy:
  provider: releases
  api_key:
    secure: k7m0Dld63XcOzfcwZ9jL1Y5O9vEsKoxt9RPa49GSe6YzcLk5Utak8ImNA9x+JKGIEiO3npp3YJ/HB457Hxjjfwl3pqAod2CJR7nFpoPac3qsy13LJj8dGPH87+crfwnfBJ9S9w6+/dWVwYjk++NjPP2ZPOBCg5An2Mhm+V/TbkQZWCjerc8nEo6SIviJNi+TocV2vDuihF3mot8iJYUKcbBn902Wns8QpvtZXISxHD30p5ImgS08dYSal8x5uFw5l70uhAm9cxEqD/QQiPb8JLbugeWnZfQtFs0q/CYZyoN3KU5rlPt8R6rnUBkCJRUqqveMVnzjHOvMLf/a4AobM4XpJadwRS2pGwuXCeYHYe79l0ILvAIW6UWPiw0lFit/7+d0VWlz0hhysYbSM+npd6vXpgT0dzd4tGsxMGqKIgI68gdpelraUlAQrllhbC7Bydh6K4ZMlTmns5K6Ofs9f2esTUhTbXoaNOCXuQaJYAL8gzDwvbUNXNf5+pDEYEaqGPGDXQCMU8qrhja3xR2/N+ki6jpsfIOtr4mCcPJGiPZcWH1comLQpfRysb4RSwnkW7auZcqCTnPkpRcbhBFFrC6Zrw1uSHbv209A+88Tt6z25Jmay5TLsXR0JBc4HCWEdKWbLsnvVcj5G75Xxh6saDOkPY5zpQeIGblwdFvZGDw=
  file: release/wp-better-settings.zip
  skip_cleanup: true
  on:
    condition: "$WP_VERSION = latest"
    php: 7.0
    tags: true
    repo: TypistTech/wp-better-settings
